@startuml

interface Cloneable {
  + clone() : Object
}

class Person {
  - name : String
  - income : Integer
  - country : Country
  - city : City
  + clone() : Person
}

class Country {
  - name : String
}

class City {
  - name : String
  + clone() : City
}

Person .up.|> Cloneable
Country .up.|> Cloneable
City .up.|> Cloneable
Person o-right-> Country
Person o--> City

@enduml